version: "3.8"
services: 
  api1:
    build: "./Softplan.Apis/Softplan.Api1"
    container_name: softplan-webapi1-container
    restart: always
    ports: 
      - "0.0.0.0:44555:80"
    networks: 
      - softplan-network
    environment:
      - API_URL=Api:44555

  api2:
    build: "./Softplan.Apis/Softplan.Api2"
    container_name: softplan-webapi2-container
    restart: always
    ports: 
      - "0.0.0.0:44333:80"
    depends_on: 
      - api1
    networks: 
      - softplan-network

networks:
  softplan-network:
    external: true

